#!/bin/bash

function fail() {
    echo "ERR: $1"
    exit 1
}

cd "$(dirname "$(realpath "$0")")/../" || fail "Cannot cd here"

FILE_OUT="src/app/styles/colors.scss"
FILE_IN="src/app/styles/theme.scss"

echo "// AUTO GENERATED BY $(basename "$0") on $(LC_ALL=C date)" > "$FILE_OUT" &&

grep -E -- '\s*--(.*?):' "$FILE_IN" |
  sed -E 's/^.*?--(.*?):.*$/\1/' |
  sort |
  uniq |
  sed -E 's/^(.*)$/\$\1: var(--\1);/' >> "$FILE_OUT" &&

echo "All OK" || fail "Some error has occurred"
