#!/bin/bash

function fail() {
    echo "ERR: $1"
    exit 1
}

cd "$(dirname "$(realpath "$0")")/../" || fail "Cannot cd here"

FILE="src/app/styles/theme.scss"

# Remove last generated content
content="$(cat "$FILE" | grep '// AUTO-GENERATED' -B 9999 | head -n -1)"
echo "$content
" > "$FILE"

# Put header
echo "// AUTO-GENERATED BY $(basename "$0") on $(LC_ALL=C date)" >> "$FILE" &&

# Generate new content
cat "$FILE" | grep -E -- '\s*--(.*?):' |
  sed -E 's/^.*?--(.*?):.*$/\1/' |
  sort |
  uniq |
  sed -E 's/^(.*)$/\$\1: var(--\1);/' >> "$FILE" &&

echo "All OK" || fail "Some error has occurred"
