/**
 * web-backend-swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type AdminTaskDeployStatus = 'default' | 'deploying' | 'done' | 'error' | 'diff';

export const AdminTaskDeployStatus = {
    Default: 'default' as AdminTaskDeployStatus,
    Deploying: 'deploying' as AdminTaskDeployStatus,
    Done: 'done' as AdminTaskDeployStatus,
    Error: 'error' as AdminTaskDeployStatus,
    Diff: 'diff' as AdminTaskDeployStatus
};