/**
 * web-backend-swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CorrectionEvaluationProgramming } from './correctionEvaluationProgramming';
import { EmptyDict } from './emptyDict';

export interface CorrectionEvaluation { 
    eval_id: number;
    points: number;
    corrected_by: number;
    cheat: boolean;
    last_modified: number;
    full_report: string;
    programming?: CorrectionEvaluationProgramming;
    quiz?: EmptyDict;
    sortable?: EmptyDict;
    text?: EmptyDict;
}