/**
 * web-backend-swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface EmailSend { 
    Subject: string;
    Body: string;
    Reply_To?: string;
    To: Array<number>;
    Bcc: Array<string>;
    Gender?: EmailSend.GenderEnum;
    KarlikSign?: boolean;
    EasterEgg?: boolean;
    Category?: EmailSend.CategoryEnum;
    Type: EmailSend.TypeEnum;
    Successful?: boolean;
}
export namespace EmailSend {
    export type GenderEnum = 'both' | 'male' | 'female';
    export const GenderEnum = {
        Both: 'both' as GenderEnum,
        Male: 'male' as GenderEnum,
        Female: 'female' as GenderEnum
    };
    export type CategoryEnum = 'hs' | 'other' | 'both';
    export const CategoryEnum = {
        Hs: 'hs' as CategoryEnum,
        Other: 'other' as CategoryEnum,
        Both: 'both' as CategoryEnum
    };
    export type TypeEnum = 'ksi' | 'events';
    export const TypeEnum = {
        Ksi: 'ksi' as TypeEnum,
        Events: 'events' as TypeEnum
    };
}