/**
 * web-backend-swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ExecutionResult } from './executionResult';

export interface Execution { 
    id: number;
    module: number;
    user: number;
    code: string;
    result: ExecutionResult;
    time: string;
    report: string;
}