/**
 * web-backend-swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ModuleQuizQuestion { 
    options: Array<string>;
    text: string;
    question: string;
    type: ModuleQuizQuestion.TypeEnum;
}
export namespace ModuleQuizQuestion {
    export type TypeEnum = 'radio' | 'checkbox';
    export const TypeEnum = {
        Radio: 'radio' as TypeEnum,
        Checkbox: 'checkbox' as TypeEnum
    };
}