/**
 * web-backend-swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ModuleType = 'general' | 'programming' | 'quiz' | 'sortable' | 'text';

export const ModuleType = {
    General: 'general' as ModuleType,
    Programming: 'programming' as ModuleType,
    Quiz: 'quiz' as ModuleType,
    Sortable: 'sortable' as ModuleType,
    Text: 'text' as ModuleType
};