/**
 * web-backend-swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ModuleSortableSortableList } from './moduleSortableSortableList';
import { ModuleType } from './moduleType';

export interface ModuleSortable { 
    id: number;
    type: ModuleType;
    name: string;
    description: string;
    autocorrect: boolean;
    max_score: number;
    state: ModuleSortable.StateEnum;
    score: number;
    sortable_list: ModuleSortableSortableList;
}
export namespace ModuleSortable {
    export type StateEnum = 'correct' | 'incorrect' | 'blank';
    export const StateEnum = {
        Correct: 'correct' as StateEnum,
        Incorrect: 'incorrect' as StateEnum,
        Blank: 'blank' as StateEnum
    };
}