/**
 * web-backend-swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type UserRole = 'admin' | 'org' | 'tester' | 'participant' | 'participant_hidden';

export const UserRole = {
    Admin: 'admin' as UserRole,
    Org: 'org' as UserRole,
    Tester: 'tester' as UserRole,
    Participant: 'participant' as UserRole,
    ParticipantHidden: 'participant_hidden' as UserRole
};