/**
 * web-backend-swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface AuthResponse { 
    accessToken: string;
    expiresIn: number;
    refreshToken: string;
    tokenType: AuthResponse.TokenTypeEnum;
}
export namespace AuthResponse {
    export type TokenTypeEnum = 'Bearer';
    export const TokenTypeEnum = {
        Bearer: 'Bearer' as TokenTypeEnum
    };
}