/**
 * web-backend-swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface BasicProfileResponseBasicProfile { 
    role: string;
    gender: string;
    email: string;
    shortInfo: string;
    profilePicture: number;
    nickName: string;
    lastName: string;
    firstName: string;
    signedIn: boolean;
    id: number;
}