/**
 * web-backend-swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CorrectionInfoTask } from './correctionInfoTask';
import { CorrectionInfoUser } from './correctionInfoUser';
import { Wave } from './wave';

export interface CorrectionInfosAllResponse { 
    correctionInfos: Array<CorrectionInfoTask>;
    waves: Array<Wave>;
    users: Array<CorrectionInfoUser>;
}