/**
 * web-backend-swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Execution } from './execution';
import { ExecutionsResponseMeta } from './executionsResponseMeta';

export interface ExecutionsResponse { 
    execs: Array<Execution>;
    meta: ExecutionsResponseMeta;
}