/**
 * web-backend-swagger
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface User { 
    id: number;
    firstName: string;
    lastName: string;
    profilePicture: string;
    gender: string;
    email?: string;
    role: string;
    score: number;
    taskNum: number;
    achievements: Array<number>;
    enabled: boolean;
    nickName: string;
    addrCountry?: string;
    schoolName?: string;
    seasons?: Array<number>;
    successful?: boolean;
    cheat?: boolean;
    tasks?: Array<number>;
    coTasks?: Array<number>;
    shortInfo?: string;
}